# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft / NeoForge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.72
neo_version_range=[21.1.0,)
loader_version_range=[4,)

# Parchment mappings (parameter names / javadoc). See https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Mod info
mod_id=smartchest
mod_name=SmartChest
mod_license=MIT
mod_version=1.21.1
mod_group_id=net.mokugyo.smartchest
mod_authors=Mokugyo
mod_description=Adds a smart, page-based chest for easier item organization.
